<?php

namespace App\Actions\LocationAccess;

use Sitebound\LocationAuth\Actions\EnsureRequestIsWithinAllowedLocation as BaseEnsureRequestIsWithinAllowedLocation;

class EnsureRequestIsWithinAllowedLocation extends BaseEnsureRequestIsWithinAllowedLocation {}
